/**
 * The trade categories offered at onboarding, in the handoff's order. A merchant
 * whose trade is not here types their own — the list is a shortcut, not a
 * closed set, so it stays a plain array rather than a union type.
 */
export const TRADES = [
  'Electrician',
  'Plumber',
  'Heating engineer (Gas Safe)',
  'Carpenter / joiner',
  'Builder',
  'Painter & decorator',
  'Plasterer',
  'Roofer',
  'Tiler',
  'Flooring fitter',
  'Kitchen & bathroom fitter',
  'Scaffolder',
  'Driveway & paving',
  'Locksmith',
  'Handyperson',
  'Landscaper / gardener',
  'Tree surgeon',
  'Window cleaner',
  'Domestic cleaner',
  'Pest control',
  'Removals / man with a van',
  'Courier & delivery',
  'Taxi & private hire',
  'Driving instructor',
  'Mobile mechanic',
  'Car valeting & detailing',
  'Hairdresser',
  'Barber',
  'Beauty therapist',
  'Nail technician',
  'Massage therapist',
  'Tattoo artist',
  'Personal trainer',
  'Sports coach',
  'Dog groomer',
  'Dog walker',
  'Childminder',
  'Private tutor',
  'Photographer',
  'Videographer',
  'Musician / DJ',
  'Event planner',
  'Caterer',
  'Mobile catering / food van',
  'Baker',
  'Florist',
  'Market trader',
  'Independent retailer',
  'Graphic designer',
  'Web developer',
  'IT support',
  'Marketing consultant',
  'Bookkeeper / accountant',
  'Business consultant',
  'Architect',
  'Surveyor',
  'Estate agent',
  'Translator',
  'Physiotherapist',
  'Osteopath',
  'Chiropractor',
  'Therapist / counsellor',
  'Optician',
  'Private dentist',
  'Veterinary practice',
  'Care worker',
  'Agency nurse',
  'Other trade or service',
] as const;
